# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JustLogin_MECS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'
  pod 'SwiftyBeaver'
  pod 'NVActivityIndicatorView'
  pod 'SnapKit', '~> 3.2.0'
  # Pods for JustLogin_MECS

  target 'JustLogin_MECSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustLogin_MECSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
      end
  end
end

end
