# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JustLogin_MECS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  # Pods for JustLogin_MECS

  target 'JustLogin_MECSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustLogin_MECSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
